import express from 'express';
import cors from 'cors';
import fetch from 'node-fetch';

const app = express();
app.use(cors());
app.use(express.json());

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const PORT = process.env.PORT || 4000;

if (!GEMINI_API_KEY) {
  console.warn('Warning: GEMINI_API_KEY is not set. The /api/ai/chat endpoint will fail until you set it.');
}

app.post('/api/ai/chat', async (req, res) => {
  try {
    const { message, filters, data } = req.body || {};

    if (!message) {
      return res.status(400).json({ error: 'message is required' });
    }

    if (!GEMINI_API_KEY) {
      return res.status(500).json({ error: 'GEMINI_API_KEY is not configured on the server.' });
    }

    const limitedTasks = Array.isArray(data?.tasks) ? data.tasks.slice(0, 200) : [];
    const limitedProvinces = Array.isArray(data?.provinces) ? data.provinces : [];

    const prompt = `You are an assistant for an infrastructure project dashboard for Indonesia.\n\n` +
      `User question:\n${message}\n\n` +
      `Current filters (may be null):\n${JSON.stringify(filters ?? {}, null, 2)}\n\n` +
      `Data (truncated for performance):\n` +
      JSON.stringify({ tasks: limitedTasks, provinces: limitedProvinces }, null, 2) +
      `\n\nRules:\n` +
      `- Only answer using the JSON data above.\n` +
      `- If the user asks for something not present in the JSON, say you don't know.\n` +
      `- Prefer short, clear summaries with bullet points where helpful.`;

    const response = await fetch(
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=' + GEMINI_API_KEY,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [
            {
              role: 'user',
              parts: [{ text: prompt }],
            },
          ],
        }),
      }
    );

    if (!response.ok) {
      const text = await response.text();
      console.error('Gemini API error:', text);
      return res.status(500).json({ error: 'Gemini API error', details: text });
    }

    const json = await response.json();
    const candidates = json.candidates || [];
    const text =
      candidates[0]?.content?.parts?.[0]?.text ||
      'No answer generated by the model.';

    res.json({ answer: text });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

app.listen(PORT, () => {
  console.log(`AI backend listening on http://localhost:${PORT}`);
});
